/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;
/**
 *
 * @author Ruben
 */
public class frmComprar extends javax.swing.JFrame {

    Negocio objN= new Negocio();
    Factura fa = new Factura();
    Factura x=new Factura();
    double st;
    double i;
    double t;
    String m;
    /**
     * Creates new form frmComprar
     */
    public frmComprar() {
        initComponents();
        listadoF();
        //listadoD();
        listadoD1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     void listadoF(){
        DefaultTableModel dt=(DefaultTableModel)listaFactura.getModel();
        dt.setRowCount(0);
        for (Factura x : objN.listadoF()) {
            Object v[]={x.getCodb(),x.getCodmp(),x.getFecha(),x.getDni(),x.getCode(),x.getSubtotal(),x.getIgv(),x.getTotal()};
            dt.addRow(v);
        }
    }
     
    void listadoD(){
        DefaultTableModel dt=(DefaultTableModel)listaDetalle.getModel();
        dt.setRowCount(0);
        for (Detalle x : objN.listadoD()) {
            ProductoDAO p = new ProductoDAO();
            Producto p1= new Producto();
            
            p1=p.buscaP(x.getCodp());
            
            Object v[]={x.getCodp(), p1.getDescripcion(), x.getCantidad(),p1.getPrecio(),x.getCantidad()*p1.getPrecio()};
            dt.addRow(v);
        }
    }
    
    void listadoDPrint(String n){
        DefaultTableModel dt=(DefaultTableModel)listaDetalle.getModel();
        dt.setRowCount(0);
        for (Detalle x : objN.listadoDPrint(m)) {
            ProductoDAO p = new ProductoDAO();
            Producto p1= new Producto();
            
            p1=p.buscaP(x.getCodp());
            
            Object v[]={x.getCodp(), p1.getDescripcion(), x.getCantidad(),p1.getPrecio(),x.getCantidad()*p1.getPrecio()};
            dt.addRow(v);
        }
    }
    
     void listadoD1(){
        DefaultTableModel dt=(DefaultTableModel)listaDetalle1.getModel();
        dt.setRowCount(0);
        for (Detalle x : objN.listadoD()) {
            Object v[]={x.getCodb(),x.getCodp(),x.getCantidad()};
            dt.addRow(v);
        }
    }
     
    void listadoFacB(String d){
        DefaultTableModel dt=(DefaultTableModel)listaFactura.getModel();
        dt.setRowCount(0);
        for (Factura x : objN.listadoF()) {
            if(x.getDni()==Integer.parseInt(d)){
              Object v[]={x.getCodb(),x.getCodmp(),x.getFecha(),x.getDni(),x.getCode(),x.getSubtotal(),x.getIgv(),x.getTotal()};
              dt.addRow(v);  
            }
        }
    }
    
    void listadoDetB(String d){
        DefaultTableModel dt=(DefaultTableModel)listaDetalle1.getModel();
        dt.setRowCount(0);
        for (Detalle x : objN.listadoD()) {
            if(x.getCodb().equals(d)){
              Object v[]={x.getCodb(),x.getCodp(),x.getCantidad()};
              dt.addRow(v);  
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        tabAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCodigoE = new javax.swing.JTextField();
        txtSubT = new javax.swing.JTextField();
        txtIGV = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cmbMetodo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaDetalle = new javax.swing.JTable();
        btnTerminarC = new javax.swing.JButton();
        btnAgregarP = new javax.swing.JButton();
        tabFactura = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDNIB = new javax.swing.JTextField();
        btnBuscarFac = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaFactura = new javax.swing.JTable();
        btnLimpiarFac = new javax.swing.JButton();
        tabDetalle = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCodFacturaB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDetalle1 = new javax.swing.JTable();
        btnBuscarDet = new javax.swing.JButton();
        btnLimpiarDet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI");

        jLabel2.setText("METODO DE PAGO");

        jLabel3.setText("CODIGO EMPLEADO");

        jLabel5.setText("FECHA");

        jLabel6.setText("TOTAL");

        jLabel8.setText("SUBTOTAL");

        jLabel9.setText("IGV");

        txtSubT.setEditable(false);

        txtIGV.setEnabled(false);

        txtTotal.setEnabled(false);

        btnEnviar.setText("GENERAR FACTURA");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel7.setText("CODIGO PRODUCTO");

        jLabel10.setText("CANTIDAD");

        txtCodigoP.setEnabled(false);

        txtCantidad.setEnabled(false);

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELEGIR", "TARJETA", "EFECTIVO" }));

        listaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod. Producto", "Descripcion", "Cantidad", "Precio Unidad", "Subtotal"
            }
        ));
        jScrollPane4.setViewportView(listaDetalle);

        btnTerminarC.setText("TERMINAR COMPRA");
        btnTerminarC.setEnabled(false);
        btnTerminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarCActionPerformed(evt);
            }
        });

        btnAgregarP.setText("AGREGAR PRODUCTO");
        btnAgregarP.setEnabled(false);
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAgregarLayout = new javax.swing.GroupLayout(tabAgregar);
        tabAgregar.setLayout(tabAgregarLayout);
        tabAgregarLayout.setHorizontalGroup(
            tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAgregarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAgregarLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabAgregarLayout.createSequentialGroup()
                        .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(98, 98, 98)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(25, 25, 25)
                                .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(79, 79, 79)
                                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbMetodo, 0, 100, Short.MAX_VALUE)
                                    .addComponent(txtCodigoE)
                                    .addComponent(txtCantidad)))
                            .addGroup(tabAgregarLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTerminarC, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addComponent(btnAgregarP))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        tabAgregarLayout.setVerticalGroup(
            tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAgregarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(18, 18, 18)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarP))
                .addGap(23, 23, 23)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTerminarC))
                .addGap(18, 18, 18)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtSubT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAgregarLayout.createSequentialGroup()
                        .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tabs.addTab("Agregar", tabAgregar);

        jLabel4.setText("DNI");

        btnBuscarFac.setText("BUSCAR");
        btnBuscarFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacActionPerformed(evt);
            }
        });

        listaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Boleta", "Cod. Metodo Pago", "Fecha", "DNI", "Cod. Empleado", "SubtTotal", "IGV", "Total"
            }
        ));
        jScrollPane3.setViewportView(listaFactura);

        btnLimpiarFac.setText("LIMPIAR");
        btnLimpiarFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabFacturaLayout = new javax.swing.GroupLayout(tabFactura);
        tabFactura.setLayout(tabFacturaLayout);
        tabFacturaLayout.setHorizontalGroup(
            tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFacturaLayout.createSequentialGroup()
                .addGroup(tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFacturaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(txtDNIB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnBuscarFac)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarFac))
                    .addGroup(tabFacturaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        tabFacturaLayout.setVerticalGroup(
            tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFacturaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDNIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFac)
                    .addComponent(btnLimpiarFac))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        tabs.addTab("Factura", tabFactura);

        jLabel11.setText("CODIGO FACTURA");

        listaDetalle1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod. Factura", "Cod. Producto", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(listaDetalle1);

        btnBuscarDet.setText("BUSCAR");
        btnBuscarDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDetActionPerformed(evt);
            }
        });

        btnLimpiarDet.setText("LIMPIAR");
        btnLimpiarDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDetalleLayout = new javax.swing.GroupLayout(tabDetalle);
        tabDetalle.setLayout(tabDetalleLayout);
        tabDetalleLayout.setHorizontalGroup(
            tabDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDetalleLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(tabDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDetalleLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(txtCodFacturaB, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnBuscarDet)
                        .addGap(35, 35, 35)
                        .addComponent(btnLimpiarDet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        tabDetalleLayout.setVerticalGroup(
            tabDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDetalleLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tabDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodFacturaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDet)
                    .addComponent(btnLimpiarDet))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        tabs.addTab("Detalle Factura", tabDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Detalle y = new Detalle();
        Producto p = new Producto();

        x.setDni(Integer.parseInt(txtDNI.getText()));
        
        String mp="";
        if(cmbMetodo.getSelectedItem().toString().equals("TARJETA")){
           mp="MP001";
        }else 
            if (cmbMetodo.getSelectedItem().toString().equals("EFECTIVO")){
                mp="MP002";
        }
        x.setCodmp(mp);
        x.setFecha(txtFecha.getText());
        x.setCode(txtCodigoE.getText());
        
        /*st= Double.parseDouble(txtSubT.getText());
        i = 0.16*st;
        t = st+i;*/
        x.setSubtotal(0);
        x.setIgv(0);
        x.setTotal(0);
        objN.adicionaF(x); 
        m= objN.buscaF(x.getDni(),x.getFecha());
        System.out.println("Codigo boleta: "+m);
       /* y.setCodb(m);
        y.setCodp(txtCodigoP.getText());
        y.setCantidad(Integer.parseInt(txtCantidad.getText()));*/
        //listadoD();
        listadoF();
        JOptionPane.showMessageDialog(null, "Se agregó La Factura");
        btnAgregarP.setEnabled(true);
        btnEnviar.setEnabled(false);
        txtCodigoP.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtDNI.setEnabled(false);
        cmbMetodo.setEnabled(false);
        txtFecha.setEnabled(false);
        txtCodigoE.setEnabled(false);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnTerminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarCActionPerformed
        // TODO add your handling code here:
            x.setSubtotal(st);
            x.setIgv(i);
            x.setTotal(t);
            txtIGV.setText(String.valueOf(i));
            txtTotal.setText(String.valueOf(t));
            System.out.println("Codigo boleta: "+m);
            objN.adicionaF2(m,x.getSubtotal(),x.getIgv(), x.getTotal());
            st=0;
            i=0;
            t=0;
        btnEnviar.setEnabled(true);
        txtCodigoP.setEnabled(false);
        txtCantidad.setEnabled(false);
        btnAgregarP.setEnabled(false);
        btnTerminarC.setEnabled(false);
        listadoF();
    }//GEN-LAST:event_btnTerminarCActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        // TODO add your handling code here:
        Detalle y = new Detalle();
        double p;
        System.out.println("Codigo boleta: "+m);
        y.setCodb(m);
        y.setCodp(txtCodigoP.getText());
        y.setCantidad(Integer.parseInt(txtCantidad.getText()));
        objN.adicionaD(y);
        listadoD();
        listadoF();
        p=objN.buscarP(y.getCodp());
        
        txtSubT.setText(String.valueOf(p));
        
       double cant = y.getCantidad();
       st=p;
        st= st+p*cant;
        i = 0.16*st;
        t = st+i;
        
        
       btnTerminarC.setEnabled(true);
       listadoDPrint(m);
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnBuscarFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacActionPerformed
        // TODO add your handling code here:
        String dni=txtDNIB.getText();
        listadoFacB(dni);
   
    }//GEN-LAST:event_btnBuscarFacActionPerformed

    private void btnLimpiarFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFacActionPerformed
        // TODO add your handling code here:
        txtDNIB.setText("");
        listadoF();
    }//GEN-LAST:event_btnLimpiarFacActionPerformed

    private void btnBuscarDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDetActionPerformed
        // TODO add your handling code here:
        String codigob= txtCodFacturaB.getText();
        listadoDetB(codigob);
    }//GEN-LAST:event_btnBuscarDetActionPerformed

    private void btnLimpiarDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDetActionPerformed
        // TODO add your handling code here:
        txtCodFacturaB.setText("");
        listadoD1();
    }//GEN-LAST:event_btnLimpiarDetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnBuscarDet;
    private javax.swing.JButton btnBuscarFac;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiarDet;
    private javax.swing.JButton btnLimpiarFac;
    private javax.swing.JButton btnTerminarC;
    private javax.swing.JComboBox<String> cmbMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable listaDetalle;
    private javax.swing.JTable listaDetalle1;
    private javax.swing.JTable listaFactura;
    private javax.swing.JPanel tabAgregar;
    private javax.swing.JPanel tabDetalle;
    private javax.swing.JPanel tabFactura;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodFacturaB;
    private javax.swing.JTextField txtCodigoE;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNIB;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtSubT;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
