/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.*;
import java.awt.BorderLayout;
import java.text.DecimalFormat;
import modelo.*;
import org.jfree.chart.*;//Para cualquier grafico
import org.jfree.data.general.DefaultPieDataset;//Circulos
//para barras y lineales
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.plot.PlotOrientation;



/**
 *
 * @author Ruben
 */
public class frmGrafico2 extends javax.swing.JFrame {

    /**
     * Creates new form frmGrafico
     */
    negocio obj = new negocio();
    DecimalFormat sd=new DecimalFormat("0.00");
    void torta(int an){
        DefaultPieDataset ds = new DefaultPieDataset();
        double sm=0;
        
        /*for(reporte1 x:obj.lisMes(an)){
            ds.setValue(x.Lmes()+"-"+x.getTotal(), x.getTotal());
        }*/
        
        for(reporte1 x:obj.lisProducto(an)){
            sm+=x.getTotal();
        }
        
        double porc;
        
        for(reporte1 x:obj.lisProducto(an)){
            porc=(x.getTotal()/sm)*100;
            ds.setValue(x.Lmes()+"-"+sd.format(porc)+"%", x.getTotal());
        }
    
        //Graficar en memoria
        JFreeChart gf=ChartFactory.createPieChart3D("Año "+an,ds);
        ChartPanel cp = new ChartPanel(gf);
        panel1.removeAll();
        panel1.setLayout(new java.awt.BorderLayout());
        panel1.add(cp,BorderLayout.CENTER);
        panel1.validate();
        
    }
    
    void barra(int an){
        DefaultCategoryDataset ds=new DefaultCategoryDataset();
        for(reporte1 x:obj.lisProducto(an)){
            ds.setValue(x.getTotal(), "ventas", x.getNombre_articulo());
        }JFreeChart gf=ChartFactory.createBarChart3D("Año "+an,"Mes" ,"Monto", ds);
        ChartPanel cp=new ChartPanel(gf);
        panel1.removeAll();
        panel1.setLayout(new java.awt.BorderLayout());
        panel1.add(cp,BorderLayout.CENTER);
        panel1.validate();
    }
    
    void lineal(int an){
        DefaultCategoryDataset ds=new DefaultCategoryDataset();
        for(reporte1 x:obj.lisProducto(an)){
            ds.setValue(x.getTotal(), "ventas", x.getNombre_articulo());
        }JFreeChart gf=ChartFactory.createLineChart("Año "+an,"Mes" ,"Monto", ds);
        ChartPanel cp=new ChartPanel(gf);
        panel1.removeAll();
        panel1.setLayout(new java.awt.BorderLayout());
        panel1.add(cp,BorderLayout.CENTER);
        panel1.validate();
    }
    public frmGrafico2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        btnCirculo = new javax.swing.JButton();
        btnBarra = new javax.swing.JButton();
        btnLineal = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese Año");

        btnCirculo.setText("Circulo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnBarra.setText("Barra");
        btnBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarraActionPerformed(evt);
            }
        });

        btnLineal.setText("Lineal");
        btnLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinealActionPerformed(evt);
            }
        });

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnCirculo)
                        .addGap(18, 18, 18)
                        .addComponent(btnBarra)
                        .addGap(18, 18, 18)
                        .addComponent(btnLineal)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCirculo)
                    .addComponent(btnBarra)
                    .addComponent(btnLineal))
                .addGap(30, 30, 30)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        // TODO add your handling code here:
        int an=Integer.parseInt(txtn.getText());
        torta(an);
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarraActionPerformed
        // TODO add your handling code here:
        int an=Integer.parseInt(txtn.getText());
        barra(an);
    }//GEN-LAST:event_btnBarraActionPerformed

    private void btnLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinealActionPerformed
        // TODO add your handling code here:
        int an=Integer.parseInt(txtn.getText());
        lineal(an);
    }//GEN-LAST:event_btnLinealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGrafico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGrafico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGrafico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGrafico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGrafico2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarra;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnLineal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
